steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast2-docker.pkg.dev/submissionmlgc-rizal-444004 /ayamgeprek /asclepius",
        ".",
      ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast2-docker.pkg.dev/submissionmlgc-rizal-444004 /ayamgeprek /asclepius",
      ]

  # Step 3: Deploy the image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "gcloud"
      - "run"
      - "deploy"
      - "asclepius"
      - "--image"
      - "asia-southeast2-docker.pkg.dev/submissionmlgc-rizal-444004 /ayamgeprek /asclepius"
      - "--platform"
      - "managed"
      - "--region"
      - "asia-southeast2"
      - "--allow-unauthenticated"
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - "asia-southeast2-docker.pkg.dev/submissionmlgc-rizal-444004 /ayamgeprek /asclepius"